server:
  port: 8080

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-service
            uri: http://localhost:8081
            predicates:
              - Path=/auth/**

          - id: notes-service
            uri: http://localhost:8082
            predicates:
              - Path=/notes/**